In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv("Classification Py data.csv", header=0)

In [3]:
df.head()

price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0   24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1   21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2   34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3   33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4   36.2       32.18     0.458     7.147  54.2      21.3       5.33   

   n_hos_beds  n_hot_rooms  rainfall     parks  Sold  avg_dist  airport_YES  \
0       5.480     11.19200        23  0.049347     0    4.0875            1   
1       7.332     12.17280        42  0.046146     1    4.9675            0   
2       7.394     46.19856        38  0.045764     0    4.9675            0   
3       9.268     11.26720        45  0.047151     0    6.0650            1   
4       8.824     11.28960        55  0.039474     0    6.0625            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_River  
0               0                         0                1  
1               1                         0                0  
2               0                         0                0  
3               1                         0                0  
4               1                         0                0

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [5]:
X = df[['price']] #independent variable

In [6]:
y = df['Sold']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

In [8]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(404, 1) (102, 1) (404,) (102,)


In [9]:
clf_LR = LogisticRegression()
clf_LR.fit(X_train, y_train)

LogisticRegression()

In [10]:
y_test_pred = clf_LR.predict(X_test)

In [11]:
y_test_pred

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0], dtype=int64)

In [12]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [13]:
confusion_matrix(y_test, y_test_pred)

array([[44, 14],
       [30, 14]], dtype=int64)

In [14]:
accuracy_score(y_test, y_test_pred)

0.5686274509803921

# K-Nearest Neighbors

In [21]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X_train)
X_train_s = scaler.transform(X_train)

In [22]:
scaler = preprocessing.StandardScaler().fit(X_test)
X_test_s = scaler.transform(X_test)

In [23]:
X_test_s

array([[ 0.03464272],
       [ 3.08888478],
       [ 0.0792302 ],
       [-1.55935952],
       [-0.12141344],
       [-0.26632274],
       [-0.18829466],
       [-0.40008517],
       [-0.68990375],
       [-0.41123203],
       [-1.50362518],
       [-0.5672882 ],
       [-0.82366618],
       [-1.31412841],
       [ 3.08888478],
       [ 0.74804233],
       [ 0.0792302 ],
       [ 1.22735769],
       [ 0.7926298 ],
       [-0.14370718],
       [ 0.16840515],
       [-0.35549769],
       [-0.21058839],
       [ 0.75918919],
       [-0.33320395],
       [ 0.09037706],
       [-0.29976335],
       [-0.32205708],
       [ 1.8292886 ],
       [-0.40008517],
       [-0.85710679],
       [-0.25517587],
       [-0.19944153],
       [-0.244029  ],
       [ 0.14611141],
       [-0.61187567],
       [-1.86032498],
       [ 3.08888478],
       [-0.86825366],
       [-1.00201608],
       [ 0.17955201],
       [-0.25517587],
       [-0.27746961],
       [-0.94628174],
       [-0.64531628],
       [-0

In [24]:
from sklearn.neighbors import KNeighborsClassifier
clf_knn_1 = KNeighborsClassifier(n_neighbors = 1)
clf_knn_1.fit(X_train_s, y_train)

KNeighborsClassifier(n_neighbors=1)

In [31]:
confusion_matrix(y_test, clf_knn_1.predict (X_test_s))

array([[32, 26],
       [22, 22]], dtype=int64)

In [35]:
accuracy_score(y_test, clf_knn_1.predict(X_test_s))

0.5294117647058824

# try L=3

In [41]:
clf_knn_3 = KNeighborsClassifier(n_neighbors = 3)
clf_knn_3.fit(X_train_s, y_train)
accuracy_score(y_test, clf_knn_1.predict(X_test_s))

0.5392156862745098

## -------

In [43]:
from sklearn.model_selection import GridSearchCV

In [44]:
params = {'n_neighbors': [1,2,3,4,5,6,7,8,9,10]}

In [47]:
grid_search_cv =  GridSearchCV(KNeighborsClassifier(), params)
# creation of object for classifier

In [48]:
grid_search_cv.fit(X_train_s, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [49]:
grid_search_cv.best_params_
# identify best out of these 10 parameters

{'n_neighbors': 7}

In [52]:
optimised_KNN = grid_search_cv.best_estimator_

In [53]:
y_test_pred = optimised_KNN.predict(X_test_s)

In [54]:
y_test_pred

array([1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0], dtype=int64)

In [55]:
confusion_matrix(y_test, y_test_pred)

array([[30, 28],
       [20, 24]], dtype=int64)

In [56]:
accuracy_score(y_test, y_test_pred)
# now we can compare accuracy score of previous models and see difference

0.5294117647058824